version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    container_name: psql
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - mnet

  server:
    depends_on:
      - postgres
    image: mtopgul/server
    container_name: server-app
    environment:
#      DB_HOST: psql
      DB_HOST: 172.21.0.1
    ports:
      - "9595:9595"
    restart: always
    networks:
      - mnet

  client:
    depends_on:
      - server
    image: mtopgul/client
    container_name: client-app
    environment:
#      SERVER_URL: server-app
      SERVER_URL: 172.21.0.1
    ports:
      - "9090:9090"
    restart: always
    networks:
      - mnet

networks:
  mnet:
    driver: bridge
