version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    container_name: psql
    ports:
      - 5432:5432
    volumes:
      - verilerim:/var/lib/postgresql/data
#      - ~/mtopgul/psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - mnet

  server:
    image: mtopgul/server
    container_name: server-app
    depends_on:
      - postgres
    environment:
      DB_HOST: psql
#      DB_HOST: 172.21.0.1
    ports:
      - "9595:9595"
    restart: always
    networks:
      - mnet

  client:
    build:
      context: ./client
      tags:
        - mtopgul/client
#    image: mtopgul/client
    container_name: client-app
    depends_on:
      - server
    environment:
      SERVER_URL: server-app
#      SERVER_URL: 172.21.0.1
    ports:
      - "9090:9090"
    restart: always
    networks:
      - mnet

volumes:
  verilerim:

networks:
  mnet:
    driver: bridge
