FROM centos:latest
ENV MSG="This is a test message."
# Exec form
# Prints $MSG. Cannot access environmet variables.
#CMD ["echo", "$MSG"]

# Shell form
# Prints 'This is a test message.'. Can access to enviroment variables.
CMD echo $MSG